import localFont from "next/font/local";
import { Outfit } from 'next/font/google';
import "./globals.css";
import FrontendLayout from "@/components/layout/FrontendLayout";  // For public-facing pages


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const outfit = Outfit({
  subsets: ['latin']
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={outfit.className}>
        <FrontendLayout>
          {children}
        </FrontendLayout>
      </body>
    </html>
  );
}
