'use client'
import type { Metadata } from 'next'
import { Provider } from 'react-redux'
import store from '@/app/redux/store';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function BasicLayout({ children, }: { children: React.ReactNode }) {
  return (
    <Provider store={store}>
      <div className="text-center p-20">
        {children}
      </div>
    </Provider>
  )
}
