'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'


import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { createContext, useEffect, useState } from 'react';


const inter = Inter({ subsets: ['latin'] })


export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export const UserContext = createContext({})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const [authData, setAuthData] = useState({})
  useEffect(() => {
    let authData;
    authData = JSON.parse(localStorage.getItem("userInfo") as string) || "";
    setAuthData(authData)

  }, []);
  return (
    // <html lang="en" className="dark">
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <UserContext.Provider value={authData}>
          {children}
        </UserContext.Provider>
      </body>
    </html>
  )
}
