import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Oswald, Roboto } from "next/font/google";
import "./globals.css";

//Components
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });
const oswald = Oswald({ subsets: ["latin"], weight: ['200', '300', '400', '500', '600', '700'], variable: '--font-oswald' });
const roboto = Roboto({ subsets: ["latin"], weight: ['100', '300', '400', '500', '700', '900'], variable: '--font-roboto' });

/* const roboto = Roboto({
  weight: '700',
  subsets: ['latin'],
  display: 'swap',
})
 */
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-gray-200">
      {/* <body className={inter.className}> */}
      {/* <body className={`${oswald.variable} ${roboto.variable}` +"w-full max-w-[1200px] mx-auto bg-white"}> */}
      <body className={`${oswald.variable} ${roboto.variable} w-full max-w-[1200px] mx-auto bg-white`}>
      {/* <body className={inter.className + "w-full max-w-[1920] mx-auto bg-white"}> */}
        <Header />
          {children}
        <Footer />
      </body>
    </html>
  );
}
