import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <div className="layout">
          <header>
            <Link href="/">

              <h1>
                <span>Just Add</span>
                <span>Marmite</span>
              </h1>
              <h2>Spread The Joy</h2>

            </Link>
          </header>

          <div className="page-content">
            {children}
          </div>

          <footer>
            <p>Copyright 2021 Just Add Marmite :)</p>
          </footer>
        </div>
      </body>
    </html>
  );
}
